project:
  type: book
book:
  title: "Frustration: One Year With R"
  author: Reece Goding
  description: "What follows is an account of my experiences from about one year of roughly daily R usage."
  chapters:
  - index.qmd
  - general_feelings.qmd
  - what_r_does_right.qmd
  - what_r_does_wrong.qmd
  - the_tidyverse.qmd
  - conclusion.qmd
  - feedback.qmd
